remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title:              Multiscale at ICPRAI'22
email:              
description:        Multiscale at ICPRAI'22
author:             Multiscale Organization team
baseurl:            "/"
url:                "https://multiscale-icprai22.github.io"
